package com.org.aws.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldDefaults;

@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "person")
public class Person implements Serializable
{
	private static final long serialVersionUID = -2869734999493632137L;

	@DynamoDBHashKey(attributeName = "personId")
	@DynamoDBAutoGeneratedKey
	String personId;

	@DynamoDBAttribute
	String name;

	@DynamoDBAttribute
	int age;

	@DynamoDBAttribute
	String email;

	@DynamoDBAttribute
	Address address;
}
